# Generated by Django 3.0.6 on 2020-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20200616_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
