# Generated by Django 3.0.6 on 2020-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_auto_20200622_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
