# Generated by Django 3.0.6 on 2020-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_userdata_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
