# Generated by Django 3.0.6 on 2020-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_userdata_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
