# Generated by Django 3.0.6 on 2020-06-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='connections',
            name='status',
            field=models.CharField(blank=True, default='sent', max_length=30, null=True),
        ),
    ]
