# Generated by Django 3.0.6 on 2020-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_company_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_model',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
